### ISSUE TITLE
Page below 550px renders blank

### ISSUE THREAD

**Issue by miyurusankalpa** [vpj/vpj.github.com#1]
I noticed this when browsing with mobile.

![549px](https://cloud.githubusercontent.com/assets/1833185/15150574/68e3e868-16eb-11e6-9953-f26a063a0360.JPG)

When tested in Firefox, page below 550px seems to move the divs way below.
![capture3](https://cloud.githubusercontent.com/assets/1833185/15150780/38e205ea-16ec-11e6-9330-a7781477b9e2.JPG)

**Comment by vpj** [comment]
When did you notice it?

I found a similar problem (not rendering on small devices) a couple of days back and fixed it.

**Comment by miyurusankalpa** [comment]
Today. 

The page renders in half, and puts a blank div with an abnormal height. you have to go to the bottom of the page to view some of the content.

**Comment by vpj** [comment]
Thanks. Will try and fix it

**Comment by vpj** [comment]
Fixed it, can you please check when you got some time. Thanks

**Comment by miyurusankalpa** [comment]
yes, now its fixed :+1:

**Comment by RoyiAvital** [comment]
Why don't you have RSS on your blog?
I couldn't register it on Feedly.

**Comment by vpj** [comment]
It's using a static site generator I wrote. It doesn't create a RSS feed yet.

**Comment by RoyiAvital** [comment]
Let me know when it does.
What about your MarkDown editor, have you left the project?

May I suggest new project?

**Comment by vpj** [comment]
Yeah, haven't worked on Wallapatta in a while.

**Comment by RoyiAvital** [comment]
Do you thing you can make Electron version (Stand alone) of [StackEdit](https://github.com/benweet/stackedit) without all the Web Integration?
Just working against local MD files.

Thank You.

**Comment by vpj** [comment]
Right now I don't I have the time for a open source project
